// <auto-generated />
namespace DotNetFloripa.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class DB_CREATE : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DB_CREATE));
        
        string IMigrationMetadata.Id
        {
            get { return "201404021141219_DB_CREATE"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
